# Generated by Django 5.x on 2026-01-09
import uuid

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trip",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("destination", models.CharField(max_length=255, blank=True)),
                ("start_date", models.DateField(null=True, blank=True)),
                ("end_date", models.DateField(null=True, blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="created_trips", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="TripMember",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ("role", models.CharField(max_length=20, choices=[("owner", "Owner"), ("editor", "Editor"), ("viewer", "Viewer")], default="owner")),
                ("status", models.CharField(max_length=20, choices=[("active", "Active")], default="active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("trip", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="memberships", to="trips.trip")),
                ("user", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="trip_memberships", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name="tripmember",
            constraint=models.UniqueConstraint(fields=["trip", "user"], name="unique_trip_member"),
        ),
        migrations.AddIndex(
            model_name="trip",
            index=models.Index(fields=["created_by"], name="trips_trip_created_by_idx"),
        ),
        migrations.AddIndex(
            model_name="tripmember",
            index=models.Index(fields=["user"], name="trips_tripmember_user_idx"),
        ),
        migrations.AddIndex(
            model_name="tripmember",
            index=models.Index(fields=["trip"], name="trips_tripmember_trip_idx"),
        ),
    ]
