# Generated by Django 5.x on 2026-01-09
import uuid

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ItineraryItem",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("location", models.CharField(max_length=255, blank=True)),
                ("start_time", models.TimeField(null=True, blank=True)),
                ("end_time", models.TimeField(null=True, blank=True)),
                ("date", models.DateField(null=True, blank=True)),
                ("sort_order", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="created_itinerary_items", to=settings.AUTH_USER_MODEL)),
                ("trip", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="itinerary_items", to="trips.trip")),
            ],
            options={"ordering": ["sort_order"]},
        ),
        migrations.CreateModel(
            name="Poll",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ("question", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="created_polls", to=settings.AUTH_USER_MODEL)),
                ("trip", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="polls", to="trips.trip")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="PollOption",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ("text", models.CharField(max_length=255)),
                ("poll", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="options", to="trips.poll")),
            ],
        ),
        migrations.CreateModel(
            name="TripInvite",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ("email", models.EmailField(max_length=254)),
                ("role", models.CharField(max_length=20, choices=[("owner", "Owner"), ("editor", "Editor"), ("viewer", "Viewer")], default="viewer")),
                ("token_hash", models.CharField(max_length=128)),
                ("status", models.CharField(max_length=20, choices=[("pending", "Pending"), ("accepted", "Accepted"), ("expired", "Expired"), ("revoked", "Revoked")], default="pending")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("invited_by", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="sent_trip_invites", to=settings.AUTH_USER_MODEL)),
                ("trip", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="invites", to="trips.trip")),
            ],
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("option", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="votes", to="trips.polloption")),
                ("poll", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="votes", to="trips.poll")),
                ("user", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="poll_votes", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name="itineraryitem",
            index=models.Index(fields=["trip", "date"], name="trips_itinerary_trip_date_idx"),
        ),
        migrations.AddIndex(
            model_name="itineraryitem",
            index=models.Index(fields=["trip", "sort_order"], name="trips_itinerary_trip_sort_idx"),
        ),
        migrations.AddIndex(
            model_name="poll",
            index=models.Index(fields=["trip", "created_at"], name="trips_poll_trip_created_idx"),
        ),
        migrations.AddIndex(
            model_name="polloption",
            index=models.Index(fields=["poll"], name="trips_polloption_poll_idx"),
        ),
        migrations.AddIndex(
            model_name="tripinvite",
            index=models.Index(fields=["trip", "email"], name="trips_invite_trip_email_idx"),
        ),
        migrations.AddIndex(
            model_name="tripinvite",
            index=models.Index(fields=["status"], name="trips_invite_status_idx"),
        ),
        migrations.AddIndex(
            model_name="vote",
            index=models.Index(fields=["poll", "user"], name="trips_vote_poll_user_idx"),
        ),
        migrations.AddConstraint(
            model_name="vote",
            constraint=models.UniqueConstraint(fields=["poll", "user"], name="unique_poll_vote"),
        ),
    ]
